---
title: Yet more on dispersal distributions
author: Bruce Kendall
date: '2019-04-16'
slug: yet-more-on-dispersal-distributions
categories:
  - Conceptual model evaluation
  - Code development
  - Planning
tags:
  - dispersal
  - Ler
---
```{r setup2, echo=FALSE, message=FALSE, cache=TRUE}
#######################################################################################
### This chunk can be deleted from any entry that lacks R code                      ###
### Set cache=FALSE during the day if you are changing the project environment;     ###
###   set it back to TRUE at the end of the day to ensure that rebuilds don't do    ###
###   unneccesary project loads.                                                    ###
#######################################################################################

# Load the project. For some reason it has to be in a separate chunck.
ProjectTemplate::load.project()
```

Once again, here's the list of distributions, with where we are on each:

* Distributions with modes at zero:
    * *Exponential power (generalized normal)*: This is in the **gnorm** package, and getting start values is probably nontrivial. It is defined on the whole real line, so a "sensible" value for the location parameter ($\mu$) is zero. It is a generalization of the normal, Laplace, and uniform distributions. It might be better just to calculate the first two directly (I've already written code for a half-normal, and could do the same for the Laplace)
    * *2Dt*: This requires writing a function to get the CDF by numerical integration, unless I can figure out the sense in which it is related to the t distribution. Not sure how to get start values.
    * *Log-sech*: This will require a custom formulation, like 2Dt. Cauchy is a special case, which we can use for start values.
    * *Inverse power*: This will require a custom formulation, like 2Dt. Not sure how to get start values.
* *Logistic*: This works out of the box, but needs to be truncated.
* *Mixture models*: this is an infinitely large set; I won't treat it here.
* Special cases of *generalized inverse Gaussian*. Code for this is in the **rmutils** package; I would have to write a wrapper for those to trap for non-numeric and vector values of $x$. I also haven't yet looked at how to get start values.
    * *Gamma*: this is in the **stats** package: `(d)gamma`. So this can be used out of the box.
    * *Inverse Gaussian (Wald)*: this is in the **actuar** package: `(d)invgauss`. This requires start values; I wrote code for this last year.
* *Wiebull*: This is in the **stats** package and works out of the box.
* *Lognormal*: This is in the **stats** package and works out of the box.


I also put a bunch of effort into the generalized gamma distribution, which generalizes the gamma, Wiebull, and exponential distributions. I've written a function that gets the start values for non-truncated data; I'd need to do more work for the truncated distributions.


I just looked again at the empirical dispersal dists. Although theere are many the have a mode slightly away from zero, there's only one that is far from zero; so I think we need to fit the central distributions, unfortunately.
