---
title: "TRACE document"
output: bookdown::pdf_document2
toc:  FALSE
header-includes: \usepackage{etoc}
bibliography: ../Bibliography.bib
---

This is a TRACE document (“TRAnsparent and Comprehensive model Evaludation”) which provides supporting evidence that our model presented in:

> **Kendall, B.E., J.L. Williams, and J.M. Levine. 20XX. Understanding the sources of variability in population spread.**

was thoughtfully designed, correctly implemented, thoroughly tested, well understood, and appropriately used for its intended purpose. 

The rationale of this document follows: 

> Schmolke A, Thorbek P, DeAngelis DL, Grimm V. 2010. Ecological modelling supporting environmental decision making: a strategy for the future. *Trends in Ecology and Evolution* 25: 479-486.

and uses the updated standard terminology and document structure in:

> Grimm V, Augusiak J, Focks A, Frank B, Gabsi F, Johnston ASA, Kułakowska K, Liu C, Martin BT, Meli M, Radchuk V, Schmolke A, Thorbek P, Railsback SF. 2014. Towards better modelling and decision support: documenting model development, testing, and analysis using TRACE. *Ecological Modelling* 280: 129-139 

and

> Augusiak J, Van den Brink PJ, Grimm V. 2014. Merging validation and evaluation of ecological models to ‘evaludation’: a review of terminology and a practical approach. *Ecological Modelling* 280: 117-128. 

\tableofcontents 

\etocsettocstyle{\vspace{1em}}{}


#	Problem formulation
\small

**This TRACE element provides supporting information on:** The decision-making context in which the model will be used; the types of model clients or stakeholders addressed; a precise specification of the question(s) that should be answered with the model, including a specification of necessary model outputs; and a statement of the domain of applicability of the model, including the extent of acceptable extrapolations. 
\normalsize

**Summary:**

> **< Provide here a concise summary of this element, e.g. brief text and/or a bullet point list. If you use lists, make sure that elements in the list match exactly the headings of the corresponding part in the text. Please keep bold font and indentation for the summary. >**

\localtableofcontents

< Your text. Any subheadings will appear in the local toc as well as the global one >

## Project objectives
The research project is designed to increase scientific understanding about the sources of variability in the rate at which a populations spreads through space. The work has the following goals:

1. Understand how variation in spread rate is affected by demographic and environmental stochasticity affecting demography; finite draws and kernel sampling affecting dispersal; and genetically driven heterogeneity in mean demography and dispersal.
2. Understand how these contributions change as habitat becomes more fragmented.
3. Understand how drift and selection lead to increases or decreases in spread variability.

## General approach
We built discrete-time, discrete-space models designed to represent, qualitatively and quantitatively, replicated greenhouse experiments in which *Arabidopsis thaliana* invades a (nearly) one-dimensional landscape [described in @Williams2016b;@Williams2018]. The model had a variety of sources of stochasticity and variability, representing the processes in the first goal statement above. We built models containing all of these factors, parameterized from various data sources. We then ran replicate simulations of the full model, as well as with one or more of the factors turned off, and calculated the variability in spread rate among and within replicates. [NEED TO DEFINE THIS PRECISELY] We used these to estimate the contributions of the individual sources of variability to the overall variability in spread rate.

NOTE: this doesn't quite address the issues that we are supposed to include here!

#	Model description 
\small

**This TRACE element provides supporting information on:**  The model. Provide a detailed written model description. For individual/agent-based and other simulation models, the ODD protocol is recommended as standard format. For complex submodels it should include concise explanations of the underlying rationale. Model users should learn what the model is, how it works, and what guided its design.
\normalsize

**Summary:**

> **< Provide here a concise summary of this element, e.g. brief text and/or a bullet point list. If you use lists, make sure that elements in the list match exactly the headings of the corresponding part in the text. Please keep bold font and indentation for the summary. >**

\localtableofcontents

## Model structure
We built discrete-time, discrete-space models designed to represent, qualitatively and quantitatively, replicated greenhouse experiments in which *Arabidopsis thaliana* invades a (nearly) one-dimensional landscape [described in @Williams2016b;@Williams2018]. The landscape for a given population was made up of "pots" aligned in a "runway;" we retained those terms in our model. The model had many sources of stochasticity and variability:

1. Seed production declines with plant density in a pot ("density dependence")
1. Individuals of a given genotype within a pot at a given time may produce different numbers of seeds ("demographic stochasticity")
2. Differences across generations, runways, and/or pots in the expected seed output (after controlling for density) of a genotype ("environmental stochasticity")
4. Variation in the distance traveled by individual seeds of a given genotype based on draws from a dispersal kernel ("dispersal sampling")
5. Differences across generations, runways, and/or pots in the dispersal kernel of a genotype ("kernel stochasticity")
6. Differences among genotypes in expected demographic and dispersal parameters ("genetic heterogeneity")
7. Variation across generations, runways, and/or pots in the genetic makeup of the population ("evolution")

## Local demography model

The primary state variable is the pre-germination number of seeds of genotype $g$ in pot $x$ at time $t$, $S_{g,x,t}$. In models with only a single genotype, the $g$ index is suppressed. These seeds germinate, survived, flowered and produced seeds; the number of produced seeds, prior to dispersal, is given by
\begin{equation}
S'_{g,x,t} = S_{g,x,t} f\left(\sum_{i=1}^G S_{i,x,t}, \mathbf{\theta_g} \right),
\end{equation}
where per-capita seed production, $f$, depends on the total local population across all $G$ genotypes and $\mathbf{\theta_g}$ is a vector of genotype-specific parameters.

There was evidence from various experiments that seed density affected seedling establishment, seedling density affected survival to reproduction, and adult density affected per-capita seed production. However, we were not able to estimate genotype-specific parameters for all of these stages; furthermore, a complex model involving all three stages resulted in a net seed production rate that was very similar to the one that could be estimated by simply relating observed $S'$ to $S$, so for simplicity and generalizability we opted to use the latter approach.

### Single genotype

### Multiple genotypes

### Demographic and environmental stochasticity

## Dispersal model

#	Data evaluation
\small

**This TRACE element provides supporting information on:**  The quality and sources of numerical and qualitative data used to parameterize the model, both directly and inversely via calibration, and of the observed patterns that were used to design the overall model structure. This critical evaluation will allow model users to assess the scope and the uncertainty of the data and knowledge on which the model is based.
\normalsize

**Summary:**

> **< Provide here a concise summary of this element, e.g. brief text and/or a bullet point list. If you use lists, make sure that elements in the list match exactly the headings of the corresponding part in the text. Please keep bold font and indentation for the summary. >**

\localtableofcontents

< Your text. Any subheadings will appear in the local toc as well as the global one >

## Ler data
### Population data

### Dispersal data
These data are in the file `2013_08_08_Exp1_Spray.csv`. This is a direct measurement of seed dispersal distance. The parents are in pots with a range of densities (these pots came from an early population experiment that was abandoned). When the parents were mature, each pot was placed next to a long piece of sticky paper the same shape as a population runway. Then the simulated rain treatment was applied. The sticky paper was divided into 1 cm bands, and the number of seeds in each band was recorded.

For this analysis, we discarded the data on pots from the "clipped" treatment.

We also used data from the first generation of the population experiment, subset to continuous runways and excluding the clipped treatment. Using data on the number of seeds falling in each pot (including the parents' pot) we calculated the ratio of generated seeds that dispersed into the runway to those that stayed in the parental pot. [WE COULD ALSO USE THESE REPS TO LOOK AT DISPERSAL, BUT SO FAR WE HAVE NOT]

NEED ASSESSMENT OF DATA QUALITY

### Seed production patterns

### Dispersal patterns

## RIL data
### Population data

### Dispersal data

### Genetic data

### Seed production patterns

### Dispersal patterns



#	Conceptual model evaluation
\small

**This TRACE element provides supporting information on:**  The simplifying assumptions underlying a model’s design, both with regard to empirical knowledge and general, basic principles. This critical evaluation allows model users to understand that model design was not ad hoc but based on carefully scrutinized considerations. 
\normalsize

**Summary:**

> **< Provide here a concise summary of this element, e.g. brief text and/or a bullet point list. If you use lists, make sure that elements in the list match exactly the headings of the corresponding part in the text. Please keep bold font and indentation for the summary. >**

\localtableofcontents

< Your text. Any subheadings will appear in the local toc as well as the global one >

#	Implementation verification
\small

**This TRACE element provides supporting information on:**  (1) whether the computer code implementing the model has been thoroughly tested for programming errors, (2) whether the implemented model performs as indicated by the model description, and (3) how the software has been designed and documented to provide necessary usability tools (interfaces, automation of experiments, etc.) and to facilitate future installation, modification, and maintenance.
\normalsize

**Summary:**

> **< Provide here a concise summary of this element, e.g. brief text and/or a bullet point list. If you use lists, make sure that elements in the list match exactly the headings of the corresponding part in the text. Please keep bold font and indentation for the summary. >**

\localtableofcontents

< Your text. Any subheadings will appear in the local toc as well as the global one >

 
#	Model output verification
\small

**This TRACE element provides supporting information on:**  (1) how well model output matches observations and (2) how much calibration and effects of environmental drivers were involved in obtaining good fits of model output and data. 
\normalsize

**Summary:**

> **< Provide here a concise summary of this element, e.g. brief text and/or a bullet point list. If you use lists, make sure that elements in the list match exactly the headings of the corresponding part in the text. Please keep bold font and indentation for the summary. >**

\localtableofcontents

< Your text. Any subheadings will appear in the local toc as well as the global one >

#	Model analysis
\small

**This TRACE element provides supporting information on:**  (1) how sensitive model output is to changes in model parameters (sensitivity analysis), and (2) how well the emergence of model output has been understood. 
\normalsize

**Summary:**

> **< Provide here a concise summary of this element, e.g. brief text and/or a bullet point list. If you use lists, make sure that elements in the list match exactly the headings of the corresponding part in the text. Please keep bold font and indentation for the summary. >**

\localtableofcontents

< Your text. Any subheadings will appear in the local toc as well as the global one >

#	Model output corroboration 
\small

**This TRACE element provides supporting information on:**  How model predictions compare to independent data and patterns that were not used, and preferably not even known, while the model was developed, parameterized, and verified. By documenting model output corroboration, model users learn about evidence which, in addition to model output verification, indicates that the model is structurally realistic so that its predictions can be trusted to some degree. 
\normalsize

**Summary:**

> **< Provide here a concise summary of this element, e.g. brief text and/or a bullet point list. If you use lists, make sure that elements in the list match exactly the headings of the corresponding part in the text. Please keep bold font and indentation for the summary. >**

\localtableofcontents

< Your text. Any subheadings will appear in the local toc as well as the global one >

# References {#references}
